### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by vyaspranjal33** [MozillaFoundation/mentorship-program#32]
language is "Gujurati" while it is "Gujarati"

name of Page= https://github.com/mozilla/leadership-training/edit/gh-pages/_articles/round-5/mentors.md 

@acabunoc

**Comment by abbycabs** [comment]
Hey @vyaspranjal33 -- you can edit the data here! https://github.com/mozilla/leadership-training/blob/gh-pages/_data/round-5/mentors.yml

**Comment by abbycabs** [comment]
closed in #33, thanks @vyaspranjal33
