### ISSUE TITLE
Links to the schedule point to the round-4  

### ISSUE THREAD

**Issue by bhavyaagg** [MozillaFoundation/mentorship-program#34]
<img width="1246" alt="final" src="https://user-images.githubusercontent.com/20207154/36012565-f9a11696-0d84-11e8-8d55-cac4295fce87.png">

The link which says "Cohort B" points to the round 4 of the Mozilla Open Leadership Training.

**Comment by abbycabs** [comment]
Fixed in #35, closing :)
