### ISSUE TITLE
Round 5 Projects Page takes more than a minute to load,  mainly due to images' size

### ISSUE THREAD

**Issue by karansapolia** [MozillaFoundation/mentorship-program#36]
We could optimize all participant images by [compressing them](https://imageoptim.com/mac) and turning the compressed images into [progressive jpegs](https://www.thewebmaster.com/dev/2016/feb/10/how-progressive-jpegs-can-speed-up-your-website/). 

Right now, when loading the page from a connection of around 4Mbps (standard 4G connection), the images load in more than a minute. This keeps the page busy loading.

**Comment by karansapolia** [comment]
[WebPage.org speed test report](https://www.webpagetest.org/result/180209_4N_1eda02dc84a701ea278439a67d5de33f/)

**Comment by abbycabs** [comment]
Thanks @karansapolia! I'm linking directly to what people uploaded in the form -- I don't have time to adjust each of the images. Happy if you (or someone reading!) would like to send a PR :)

**Comment by abbycabs** [comment]
dropping this here in case I (or @karansapolia? or someone else?) have time to address this later: https://www.howtogeek.com/tips/how-to-compress-a-folder-of-images-easily-from-the-command-line/
