### ISSUE TITLE
Nick Wood picture on Cohort A

### ISSUE THREAD

**Issue by ThePhoenixBird** [MozillaFoundation/mentorship-program#39]
I don't know if it's a joke or intentional, but it seems inappropriate to put a picture with a caption that reads "**I WILL KILL YOU**" on it. 

Not very leader-ish

**Comment by abbycabs** [comment]
I'd tag Nick and ask him but he didn't give a github ID. I'll email this issue to him :) Thanks @ThePhoenixBird!

**Comment by Nickwood225** [comment]
Oops. A friend turned my profile pic into a meme which got put back in my image folder.
Obvs the thumbnails were cropped and so I pulled out the wrong version for the submission. I haven’t even been able to find the Cohort A images in here so I have no idea how to rectify the issue.  If you can let me know how to do that I’ll change it.

**Comment by abbycabs** [comment]
Thanks @Nickwood225 it's linked here: https://github.com/mozilla/leadership-training/blob/gh-pages/_data/round-5/participants.yml#L642

Feel free to send a PR & update with a new image :)

**Comment by abbycabs** [comment]
Updated Here: https://github.com/mozilla/leadership-training/commit/d9f429116e0a0920da9e6e51b6dd733ee840aa09

Closing 🎉 thanks everyone
