### ISSUE TITLE
Feedback on for OL5 (Week 3+)

### ISSUE THREAD

**Issue by abbycabs** [MozillaFoundation/mentorship-program#48]
Hello all!

How did you find Week 3: Project Communication & Community Building or your time in the program generally?

* What went well?
* What could be better?
* Is there anything you'd like to see more or less of during the program?

This program is here to help you! If there's anything you'd like to let us know, this is a great place. You're always welcome to send me an email (abby AT mozillafoundation.org)

**Comment by booyaa** [comment]
> What went well?

Really like the variety of having guest speakers, every week has felt fresh and not repetitive.

> What could be better?

Guest speaker setup, I know how hard it is to get screen sharing working from my own difficulties of hosting remote talks for my meetups. Looks like you got it covered though: #49 

> Is there anything you'd like to see more or less of during the program?

Nothing comes to mind at the moment.

Still continuing to enjoy this program, glad I signed up.

**Comment by abbycabs** [comment]
Updated the title to make this an ongoing feedback issue -- thanks @booyaa for some early thoughts!
