### ISSUE TITLE
Updating "Facilitating Awesome Events"

### ISSUE THREAD

**Issue by abbycabs** [MozillaFoundation/mentorship-program#50]
We got really excellent feedback last round on the content for this session (especially right before MozFest). But some of our community facilitators found this to be a pretty long session to spend talking to the audience (we only had one person facilitating per cohort! So, it was a good 40min of them talking.

Things to change this round (open to pushback & other suggestions!):

* Split the lesson this into two parts and have two different guest facilitators deliver their sections
* Add something less lectury like a breakout room (participants LOVE these) or silent etherpadding

I'll need these things done by EOD Tuesday to send to potential guest facilitators for the week after.

- [x] Split the deck into two presentations
- [x] Update what is put in the etherpad for participants to see
- [x] (optional) If you have any additional notes for the facilitator, you can add them to the facilitators guide

Current deck: https://docs.google.com/presentation/d/1SgOq_ygsOTOjPlmvvVM4ZDm0PYtlyg4krnnhkHvkLO0/edit#slide=id.p
Current etherpad content: https://public.etherpad-mozilla.org/p/ol5-facilitating-awesome-events
Annotated Facilitators Guide: https://docs.google.com/document/d/1P_Dfx1TVwpGO9OdyAQcCvpqM69LYsRK-OOYmkpm7qJA/edit#heading=h.f5wxzzbdkafr

Huge thanks to @chadsansing for helping out here!

**Comment by chadsansing** [comment]
Materials updated & ready for review, @acabunoc.

**Comment by chadsansing** [comment]
Sarah will review.

cc @Saallen

**Comment by abbycabs** [comment]
delivered!
