### ISSUE TITLE
Links to Past Rounds 1-3 result in 404

### ISSUE THREAD

**Issue by BenjaminHCCarr** [MozillaFoundation/mentorship-program#51]
On https://foundation.mozilla.org/opportunity/mozilla-open-leaders/past-rounds/

Rounds 1-3 on the website result in a 404:

https://mozilla.github.io/leadership-training/round-1/
https://mozilla.github.io/leadership-training/round-2/
https://mozilla.github.io/leadership-training/round-3/

I am interested in applying to MozOpenLeaders so seeing past projects will help me get a better sense of how to tailor the project I submit.

**Comment by abbycabs** [comment]
Sorry I missed this earlier @BenjaminHCCarr!

The links were wrong, they've been updated now:
https://foundation.mozilla.org/opportunity/mozilla-open-leaders/past-rounds/

https://mozilla.github.io/leadership-training/past-rounds/round-1/
https://mozilla.github.io/leadership-training/past-rounds/round-2/
https://mozilla.github.io/leadership-training/past-rounds/round-3/
