### ISSUE TITLE
Feedback on Week 2

### ISSUE THREAD

**Issue by abbycabs** [MozillaFoundation/mentorship-program#56]
Hello all!
How did you find Week 2: Introductions & Open by Design?

* What went well?
* What could be better?
* Is there anything you'd like to see more or less of during the program?

This program is here to help you! If there's anything you'd like to let us know, this is a great place. You're always welcome to send me an email (abby AT mozillafoundation.org)

**Comment by dbild** [comment]
There is a phone call-in option for zoom, right? If so, could we add the number to the calendar invite and the google notes? (one of my mentees was having internet issues, so left the call and was unable to rejoin)

**Comment by abbycabs** [comment]
Great idea! Thanks Dave
